M48
; DRILL file {KiCad (6.0.7)} date Fri Sep  9 14:19:00 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-09-09T14:19:00-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
%
G90
G05
T1
X80.0Y-50.0
X80.0Y-52.5
X80.0Y-62.5
X80.0Y-65.0
X90.0Y-56.0
X90.0Y-58.5
T0
M30
